Не забываем импортировать NumPy!

In [1]:
import numpy as np

Темы


*   Основы работы с массивами numpy

*   Матрицы в numpy

*   Линейная алгебра в numpy

Тема: Линейная алгебра в NumPy

Решение систем линейных уравнений.

Норма вектора и матрицы.

Собственные значения и собственные векторы.

Сингулярное разложение (SVD), холецкий, кьюар.

В этот раз подробнее рассмотрим np.linalg и работу с некоторыми задачами линейной алгебры.

np.linalg является подмодулем библиотеки NumPy, который предоставляет функции для работы с линейной алгеброй. Этот подмодуль содержит множество функций, позволяющих выполнять различные операции и вычисления, связанные с линейной алгеброй, такие как вычисление определителя, обратной матрицы, собственных значений и векторов, разложение на сингулярные значения, решение систем линейных уравнений и многое другое.

Решение систем линейных уравнений состоит в нахождении значений переменных, удовлетворяющих всем уравнениям в системе. В NumPy для решения таких систем используется функция np.linalg.solve().

Система линейных уравнений обычно записывается в матричной форме Ax = b, где A - матрица коэффициентов, x - вектор переменных, b - вектор правой части уравнений.
Например, решение для следующей системы уравнений:
\begin{cases}
   2x + 3y = 5,
   \\
   4x - y = -2
 \end{cases}



In [2]:
# Матрица коэффициентов
A = np.array([[2, 3], [4, -1]])

# Вектор правой части уравнений
b = np.array([5, -2])

# Решение системы линейных уравнений
solution = np.linalg.solve(A, b)

print("Решение системы уравнений:")
print("x =", solution[0])
print("y =", solution[1])

Решение системы уравнений:
x = -0.07142857142857145
y = 1.7142857142857142


Определитель, обратная матрица и ранг.

С помощью np.linalg мы наконец-то можем вычислить определитель, обратную матрицу и ранг матрицы.



In [4]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 10]])

# Вычисление определителя матрицы
determinant = np.linalg.det(matrix)

# Вычисление обратной матрицы
inverse_matrix = np.linalg.inv(matrix)

# Вычисление ранга матрицы
rank = np.linalg.matrix_rank(matrix)

print("Определитель матрицы:", determinant)
print("Обратная матрица:")
print(inverse_matrix)
print("Ранг матрицы:", rank)

Определитель матрицы: -2.9999999999999996
Обратная матрица:
[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]
Ранг матрицы: 3


## Разложения матриц

np.linalg предоставляет функции для некоторых разложений матриц, например:


1. Сингулярное разложение ($SVD$)

$SVD$ представляет собой метод разложения матрицы на произведение трех более простых матриц:
$A=U⋅Σ⋅V^T$, где
A - исходная матрица,
U и V - ортогональные матрицы (матрицы, удовлетворяющие условию
$U ^T⋅U=I$ и $V^T⋅V=I$, где
$I$ - единичная матрица), а
$Σ$ - диагональная матрица, содержащая сингулярные значения исходной матрицы.

$SVD$ широко используется в анализе данных, сжатии изображений, рекомендательных системах и других областях.

In [14]:
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

# Вычисление сингулярного разложения
U, Sigma, Vt = np.linalg.svd(A)

print("U:")
print(U)
print("Sigma:")
print(Sigma)
print("Vt:")
print(Vt)


U:
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Sigma:
[9.52551809 0.51430058]
Vt:
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


2. Разложение Холецкого:

Разложение Холецкого применяется к симметричным и положительно определенным матрицам. Оно представляет матрицу
$A$ в виде произведения
$A=L⋅L^T$, где
$L$ - нижнетреугольная матрица.

Разложение Холецкого используется в решении систем линейных уравнений, симуляции случайных процессов, фильтрации сигналов и других приложениях.

In [15]:
B = np.array([[4, 12, -16],
              [12, 37, -43],
              [-16, -43, 98]])

# Вычисление разложения Холецкого
L = np.linalg.cholesky(B)

print("Lower triangular matrix L:")
print(L)

#Проверим
reconstructed_B = np.dot(L, L.T)

print("\nИсходная матрица B:")
print(B)
print("\nВосстановленная матрица B из разложения Холецкого:")
print(reconstructed_B)
print("Равны ли эти B и reconstructed_B?", np.allclose(B, reconstructed_B))

Lower triangular matrix L:
[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]

Исходная матрица B:
[[  4  12 -16]
 [ 12  37 -43]
 [-16 -43  98]]

Восстановленная матрица B из разложения Холецкого:
[[  4.  12. -16.]
 [ 12.  37. -43.]
 [-16. -43.  98.]]
Равны ли эти B и reconstructed_B? True


Функция np.allclose() проверяет, равны ли соответствующие элементы двух массивов с некоторой допустимой погрешностью.

3. QR разложение:

QR разложение представляет матрицу
$A$ в виде произведения
$A=QR$, где
$Q$ - ортогональная матрица, а
$R$ - верхнетреугольная матрица.

QR разложение используется в задачах линейной регрессии, вычислении собственных значений матрицы, ортогонализации базиса и других задачах.

In [18]:
C = np.array([[1, -1, 2],
              [1, 1, 0],
              [1, -1, 2]])

# Вычисление QR разложения
Q, R = np.linalg.qr(С)

print("Q (orthogonal matrix):")
print(Q)
print("R (upper triangular matrix):")
print(R)


reconstructed_C = np.dot(Q, R)

print("\nИсходная матрица C:")
print(C)
print("\nВосстановленная матрица B из QR разложения:")
print(reconstructed_C)
print("Равны ли эти C и reconstructed_C?", np.allclose(C, reconstructed_C))

Q (orthogonal matrix):
[[-0.57735027  0.40824829 -0.70710678]
 [-0.57735027 -0.81649658  0.        ]
 [-0.57735027  0.40824829  0.70710678]]
R (upper triangular matrix):
[[-1.73205081e+00  5.77350269e-01 -2.30940108e+00]
 [ 0.00000000e+00 -1.63299316e+00  1.63299316e+00]
 [ 0.00000000e+00  0.00000000e+00 -5.55111512e-17]]

Исходная матрица C:
[[ 1 -1  2]
 [ 1  1  0]
 [ 1 -1  2]]

Восстановленная матрица B из QR разложения:
[[ 1.00000000e+00 -1.00000000e+00  2.00000000e+00]
 [ 1.00000000e+00  1.00000000e+00 -6.23553335e-16]
 [ 1.00000000e+00 -1.00000000e+00  2.00000000e+00]]
Равны ли эти C и reconstructed_C? True


## Норма вектора и матрицы:

В NumPy для вычисления нормы вектора (длины вектора) можно воспользоваться функцией numpy.linalg.norm(). Эта функция принимает вектор и опциональный параметр ord, который определяет порядок нормы. Порядок по умолчанию (если не указан) равен 2, что соответствует Евклидовой норме.

In [19]:
vector = np.array([3, 4])
print(np.linalg.norm(vector))


5.0


С помощью функции numpy.linalg.norm() в NumPy также можно вычислить норму матрицы

In [20]:
matrix = np.array([[1, 2], [3, 4]])
print(np.linalg.norm(matrix))


5.477225575051661


## Собственные значения и собственные векторы



Собственные значения и собственные векторы - это важные концепции линейной алгебры, которые широко используются в различных областях, включая машинное обучение, физику, инженерные науки и другие. В NumPy для вычисления собственных значений и собственных векторов матрицы используется функция numpy.linalg.eig().

Собственные значения и собственные векторы:
Собственные значения (eigenvalues) и собственные векторы (eigenvectors) матрицы
$A$ определяются таким образом, что:
Для квадратной матрицы
$A$ и скаляра
$λ$ существует ненулевой вектор
$v$, такой что
$Av=λv$. Здесь
$v$ называется собственным вектором, а
$λ$ - собственным значением.



In [21]:
matrix = np.array([[1, 2], [2, 1]])

# Вычисление собственных значений и собственных векторов
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Собственные значения:", eigenvalues)
print("Собственные векторы:")
for i in range(len(eigenvalues)):
    print("Собственное значение:", eigenvalues[i])
    print("Соответствующий собственный вектор:", eigenvectors[:,i])


Собственные значения: [ 3. -1.]
Собственные векторы:
Собственное значение: 3.0000000000000004
Соответствующий собственный вектор: [0.70710678 0.70710678]
Собственное значение: -0.9999999999999996
Соответствующий собственный вектор: [-0.70710678  0.70710678]
