In [ ]:
import numpy as np

В NumPy матрицы представляют собой двумерные массивы, которые обладают особыми свойствами и функциями, оптимизированными для линейной алгебры и работы с матрицами.


Матрицу можно создать, передав список списков (или другой итерируемый объект) в функцию np.array()

In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


NumPy предоставляет некоторые специальные функции для создания определенных типов матриц.
1. Матрица из нулей (np.zeros()):

Матрица из нулей состоит из всех элементов, равных нулю.

In [ ]:
# Создание матрицы из нулей размером 2x3
zeros_matrix = np.zeros((2, 3))
print(zeros_matrix)


[[0. 0. 0.]
 [0. 0. 0.]]


2. Матрица из единиц (np.ones()):

Матрица из единиц состоит из всех элементов, равных единице.

In [ ]:
# Создание матрицы из единиц размером 3x2
ones_matrix = np.ones((3, 2))
print(ones_matrix)


[[1. 1.]
 [1. 1.]
 [1. 1.]]


3. Единичная матрица (np.eye()):

Единичная матрица (или единичный оператор) - это квадратная матрица, у которой все элементы на главной диагонали равны 1, а все остальные равны 0.

In [ ]:
# Создание единичной матрицы размером 3x3
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Диагональная матрица (np.diag()):

Диагональная матрица имеет ненулевые элементы только на главной диагонали.

In [ ]:
# Создание диагональной матрицы размером 3x3
diagonal_matrix = np.diag([1, 2, 3])
print(diagonal_matrix)


[[1 0 0]
 [0 2 0]
 [0 0 3]]


5. Матрица с заданным значением (np.full()):

Матрица с заданным значением содержит все элементы, равные определенному значению

In [ ]:
# Создание матрицы с заданными значениями
constant_matrix = np.full((2, 3), 5)
print(constant_matrix)


[[5 5 5]
 [5 5 5]]


6. NumPy также предоставляет методы для генерации матриц с случайными значениями.

In [ ]:
random_matrix1 = np.random.rand(2, 3)
print(random_matrix1)

random_matrix2 = np.random.randint(10, size=(3, 2))
print(random_matrix2)


[[0.96724696 0.85198786 0.94743091]
 [0.71636589 0.77264582 0.34596159]]
[[2 5]
 [4 5]
 [7 1]]


Это некоторые из наиболее распространенных предустановленных матриц в NumPy.

В NumPy у массивов, включая матрицы, есть несколько основных атрибутов, которые предоставляют информацию о их форме и размере. Некоторые из них:

1. shape:

Атрибут shape возвращает кортеж, представляющий размерность массива. Для матрицы это будет кортеж с двумя элементами, где первый элемент представляет количество строк, а второй элемент - количество столбцов.

2. ndim:

Атрибут ndim возвращает количество измерений (осей) массива. Для матрицы это всегда будет 2, поскольку матрица является двумерным массивом.

3. size:

Атрибут size возвращает общее количество элементов в массиве.

4. real и imag:

Если массив содержит комплексные числа, атрибуты real и imag представляют вещественную и мнимую части соответственно.

In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Форма (shape) матрицы:", matrix.shape)
print("Количество измерений (ndim) матрицы:", matrix.ndim)
print("Общее количество элементов (size) матрицы:", matrix.size)


Форма (shape) матрицы: (3, 3)
Количество измерений (ndim) матрицы: 2
Общее количество элементов (size) матрицы: 9


In [ ]:
arr_complex = np.array([[1 + 2j, 3 + 4j], [5 + 6j, 7 + 8j]])

print("Вещественная часть (real):", arr_complex.real)
print("Мнимая часть (imag):", arr_complex.imag)


Вещественная часть (real): [[1. 3.]
 [5. 7.]]
Мнимая часть (imag): [[2. 4.]
 [6. 8.]]


В прошлом занятии были рассмотрены арифметические операции на массивах. Тот же функционал присутствует касательно матриц.

* Сложение и вычитание:

Сложение и вычитание матриц происходит поэлементно. Для этого используются операторы + и -.

In [ ]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

print(matrix1 + matrix2)


[[ 6  8]
 [10 12]]


In [ ]:
print(matrix1 - matrix2)

[[-4 -4]
 [-4 -4]]


* Умножение:

Умножение матриц также может быть поэлементным или матричным, в зависимости от использования оператора * или функции np.dot()

In [ ]:
print(matrix1 * matrix2)


[[ 5 12]
 [21 32]]


In [ ]:
print(np.dot(matrix1, matrix2))


[[19 22]
 [43 50]]


* Деление:

Деление матриц также происходит поэлементно. Используется оператор /

In [ ]:
print(matrix1 / matrix2)


[[0.2        0.33333333]
 [0.42857143 0.5       ]]


Также NumPy с помощью своих методов предоставляет возможность транспонировать матрицу, найти определитель,ранг, след, обратную матрицу и другое.

Транспонирование матрицы можно выполнить с помощью метода .T или функции np.transpose()

In [ ]:
print (matrix1.T)


[[1 3]
 [2 4]]


In [ ]:
print (np.transpose(matrix1))


[[1 3]
 [2 4]]


След можно найти с помощью np.trace().

In [ ]:
print(np.trace(matrix1))


5


Определитель, обратную матрицу и ранг можно найти с помощью функций np.linalg.det() и np.linalg.inv(), их и подмодуль np.linalg рассмотрим чуть позже


In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix[:, 1].sum())

15
