## Введение в NumPy

NumPy (Numerical Python) - это библиотека для языка программирования Python, предназначенная для работы с многомерными массивами и матрицами, а также содержащая большое количество функций для выполнения операций линейной алгебры, статистики, случайных чисел и многого другого. Она является одной из основных библиотек для научных вычислений в Python и широко используется в областях, таких как анализ данных, машинное обучение, обработка изображений, численное моделирование и других.

#### Зачем нужен NumPy?

* Эффективность: NumPy обеспечивает высокую производительность и эффективность при работе с массивами данных благодаря своей реализации на языке программирования C. Это позволяет обрабатывать большие объемы данных быстрее, чем с помощью обычных списков Python.

* Многомерные массивы: NumPy предоставляет объект ndarray, который позволяет эффективно хранить и оперировать многомерными массивами данных. Это делает его идеальным инструментом для работы с матрицами, изображениями, временными рядами и другими типами данных, которые могут быть представлены в виде массивов.

* Богатый функционал: Библиотека NumPy содержит множество функций для выполнения различных операций, таких как арифметические операции, статистические вычисления, сортировка, фильтрация, решение линейных уравнений и многое другое. Это делает NumPy мощным инструментом для научных и инженерных вычислений.

Преимущества использования NumPy перед обычными списками Python:

* Высокая производительность: Операции с массивами NumPy выполняются гораздо быстрее, чем операции с обычными списками, благодаря использованию оптимизированных алгоритмов на языке C.

* Удобство и простота: NumPy предоставляет простой и удобный интерфейс для работы с массивами, что делает код более читаемым и понятным.

* Больше функций: NumPy предоставляет богатый выбор функций для выполнения операций над массивами, что упрощает решение широкого спектра задач, связанных с научными вычислениями и анализом данных.

* Интеграция с другими библиотеками: NumPy тесно интегрируется с другими популярными библиотеками Python, такими как SciPy, Matplotlib и Pandas, что делает его частью экосистемы инструментов для научных и инженерных вычислений.

## Создание массивов NumPy

Обычно NumPy импортируется под псевдонимом **np** для удобства использования. Это общепринятое сокращение.

In [ ]:
import numpy as np

В NumPy для создания одномерных массивов можно использовать функцию numpy.array(), которая принимает список (или другой итерируемый объект) в качестве аргумента и создает из него одномерный массив.

In [ ]:
# Создание одномерного массива из списка
arr1 = np.array([1, 2, 3, 4, 5])
print("Массив arr1:", arr1)

# Создание одномерного массива из кортежа
arr2 = np.array((6, 7, 8, 9, 10))
print("Массив arr2:", arr2)

# Создание одномерного массива из диапазона чисел
arr3 = np.arange(1, 6)  #Массив с числами от 1 до 5 (не включая 6)
print("Массив arr3:", arr3)


Массив arr1: [1 2 3 4 5]
Массив arr2: [ 6  7  8  9 10]
Массив arr3: [1 2 3 4 5]


Для создания многомерных массивов также используется функция numpy.array()

In [ ]:
# Создание трехмерного массива из списка списков
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Двумерный массив arr2d:")
print(arr2d)

# Создание трехмерного массива
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("Трехмерный массив arr3d:")
print(arr3d)

# Создание массива размером 2x3, заполненный случайными числами от 0 до 1
random_arr = np.random.rand(2, 3)
print("Массив random_arr (случайные числа):")
print(random_arr)


Двумерный массив arr2d:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Трехмерный массив arr3d:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Массив random_arr (случайные числа):
[[0.59123407 0.4713403  0.10605412]
 [0.37402519 0.68914548 0.73225305]]


В NumPy есть несколько встроенных функций для создания массивов с определенными значениями.

1. np.zeros(shape): Создает массив заданной формы (shape), заполненный нулями.

In [ ]:
zeros_arr = np.zeros((2, 3))
print("Массив, заполненный нулями:")
print(zeros_arr)


Массив, заполненный нулями:
[[0. 0. 0.]
 [0. 0. 0.]]


2. np.ones(shape): Создает массив заданной формы (shape), заполненный единицами.

In [ ]:
ones_arr = np.ones((3, 2))
print("Массив, заполненный единицами:")
print(ones_arr)


Массив, заполненный единицами:
[[1. 1.]
 [1. 1.]
 [1. 1.]]


3. np.empty(shape): Создает массив заданной формы (shape), но не инициализирует его значениями. Вместо этого в массиве могут оказаться произвольные значения, которые находились в соответствующей области памяти до создания массива.


In [ ]:
empty_arr = np.empty((2, 2))
print('"Пустой" массив:')
print(empty_arr)


Пустой массив:
[[4.93350080e-310 0.00000000e+000]
 [6.95121561e-310 6.95121561e-310]]


4. np.arange(start, stop, step): Создает одномерный массив со значениями от start до stop с заданным шагом step.

In [ ]:
arange_arr = np.arange(0, 10, 2)
print("Массив, созданный с помощью arange():")
print(arange_arr)


Массив, созданный с помощью arange():
[0 2 4 6 8]


5. np.linspace(start, stop, num): Создает одномерный массив с *num* равномерно распределенных элементов в диапазоне от start до stop (включительно).

In [ ]:
linspace_arr = np.linspace(0, 1, 5)
print("Массив, созданный с помощью linspace():")
print(linspace_arr)


Массив, созданный с помощью linspace():
[0.   0.25 0.5  0.75 1.  ]


## Основные операции с массивами NumPy

Индексация и срезы массивов в NumPy работают аналогично спискам в Python, но с дополнительными возможностями для работы с многомерными массивами

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Обращение к элементу массива по индексу
print("Первый элемент:", arr[0])

print("Последний элемент:", arr[-1])

print("Срез от второго до четвертого элемента:", arr[1:4])

print("Срез с шагом 2:", arr[::2])


Первый элемент: 1
Последний элемент: 5
Срез от второго до четвертого элемента: [2 3 4]
Срез с шагом 2: [1 3 5]


Для обращения к элементу двумерного массива используется массив индексов

In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Элемент во второй строке и втором столбце:", arr_2d[1, 1])

print("Подмассив с двухмерного массива:")
print(arr_2d[:2, 1:])


print("Срез с шагом 2 по столбцам:")
print(arr_2d[:, ::2])


Элемент во второй строке и втором столбце: 5
Подмассив с двухмерного массива:
[[2 3]
 [5 6]]
Срез с шагом 2 по столбцам:
[[1 3]
 [4 6]
 [7 9]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
indices = np.array([0, 2, 4])
print(arr[indices])

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Создание массива индексов для строк и столбцов
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])

# Индексация массива arr_2d с использованием массивов индексов
result = arr_2d[row_indices, col_indices]

print(result)

[1 3 5]
[2 6 7]


Индексация и срезы с помощью условий:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[arr > 2])

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[arr_2d > 5])


[3 4 5]
[6 7 8 9]


Индексация и срезы в многомерных массивах:
В многомерных массивах вы можете использовать несколько индексов или срезов для доступа к элементам или подмассивам. Срезы в многомерном массиве также задаются с помощью start:stop:step для каждого измерения, разделенных запятыми.

In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[:2, 1:])


[[2 3]
 [5 6]]


In [ ]:
print(arr2d[:, ::2])


[[1 3]
 [4 6]
 [7 9]]


В NumPy арифметические операции с массивами выполняются поэлементно:

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 + arr2)
print(arr1 + 10)



[5 7 9]
[11 12 13]


In [ ]:
print(arr1 - arr2)
print(arr1 - 10)


[-3 -3 -3]
[-9 -8 -7]


In [ ]:
print(arr1 * arr2)
print(arr1 * 10)


[ 4 10 18]
[10 20 30]


In [ ]:
print(arr1 / arr2)
print(arr1 / 10)


[0.25 0.4  0.5 ]
[0.1 0.2 0.3]


In [ ]:
print(arr1 ** arr2)
print(arr1 ** 2)


[  1  32 729]
[1 4 9]


NumPy предоставляет множество базовых математических функций для работы с массивами данных. Эти функции могут быть применены к массивам поэлементно. Ниже представленны несколько примеров базовых математических функций. Более подробный список функций и дополнительные возможности можно найти в официальной документации.

In [ ]:
arr1 = np.array([0, np.pi/2, np.pi])

#np.sin(): Вычисляет синус угла для каждого элемента массива.
print("Синус элементов массива:", np.sin(arr1))

#np.cos(): Вычисляет косинус угла для каждого элемента массива.
print("Косинус элементов массива:", np.cos(arr1))

#np.tan(): Вычисляет тангенс угла для каждого элемента массива.
print("Тангенс элементов массива:", np.tan(arr1))


Синус элементов массива: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Косинус элементов массива: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
Тангенс элементов массива: [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [ ]:
arr2 = np.array([1, 2, 3])

#np.exp(): Вычисляет экспоненту (e^x) для каждого элемента массива.
print("Экспонента для каждого элемента массива:", np.exp(arr2))


Экспонента для каждого элемента массива: [ 2.71828183  7.3890561  20.08553692]


In [ ]:
arr3 = np.array([1, np.e, np.e**2])
#np.exp(): Вычисляет натуральный для каждого элемента массива.
print("Натуральный логарифм для каждого элемента массива:", np.log(arr3))


Натуральный логарифм для каждого элемента массива: [0. 1. 2.]


In [ ]:
arr4 = np.array([4, 9, 16])

#np.exp(): Вычисляет квадратный корень для каждого элемента массива.
print("Квадратный корень для каждого элемента массива:", np.sqrt(arr4))


Квадратный корень для каждого элемента массива: [2. 3. 4.]


Если мы работаем с векторами, мы также можем вычислить их скалярное и векторное произведение с помощью функций np.dot() и np.cross().

In [ ]:
vec1 = np.array([1, 2, 3])
vec2 = np.array([4, 5, 6])

print("Векторное произведение векторов vec1 и vec2:",np.cross(vec1, vec2))
print("Скалярное произведение векторов vec1 и vec2:",np.dot(vec1, vec2))

Векторное произведение векторов vec1 и vec2: [-3  6 -3]
Скалярное произведение векторов vec1 и vec2: 32


Помня определение смешанного произведения $(a×b)⋅c$, можем вычислить и его тоже с помощью комбинации функций np.cross() и np.dot()

In [ ]:
vec3 = np.array([7, 8, 9])

print("Смешанное произведение векторов vec1, vec2 и vec3:", np.dot(np.cross(vec1, vec2), vec3))

Смешанное произведение векторов vec1, vec2 и vec3: 0


## Немного практики

###1)
Создайте двумерный массив размером 4x5, заполненный случайными числами  в диапазоне от 0 до 10.
Найдите среднее значение всех элементов массива.
Создайте новый массив, в котором каждый элемент оригинального массива будет увеличен на среднее значение из предыдущего шага и для каждого элемента найдите его синус, экспоненту, натуральный логарифм и квадратный корень.

###2)
Создайте двумерный массив размером 6x6, заполненный числами от 0 до 35.
Выделите и выведите на экран подмассив, состоящий из 3-х строк и 3-х столбцов второй четверти массива.
Создайте массив из всех четных элементов исходного массива и выведите его на экран.

###3)
Создайте два вектора vec1 и vec2 длиной по 3 элемента. Заполните их любыми целыми числами по своему выбору.
Найдите и выведите на экран скалярное
и векторное произведение векторов vec1 и vec2.
Создайте третий вектор vec3 аналогично первым двум
и вычислите смешанное произведение $(vec1 × vec2) ⋅ vec3$ и выведите результат на экран.