## Introduction to NumPy

NumPy (Numerical Python) is a library for the Python designed to work with multidimensional arrays and matrices. It also contains a large number of functions for performing linear algebra, statistics, random numbers, and much more. It is one of the main libraries for scientific computing in Python and is widely used in fields such as data analytics, machine learning, image processing, numerical modeling and others.

Benefits of NumPy:

* Efficiency: NumPy provides high performance and efficiency when working with  data arrays thanks to its implementation in the C programming language. It allows you to process large amounts of data faster than regular Python lists.

* Multidimensional Arrays: NumPy provides the ndarray object, which allows you to efficiently store and manipulate multidimensional arrays of data. This makes it an ideal tool for working with matrices, images, time series, and other types of data that can be represented as arrays.

* Rich Functionality: The NumPy library contains many functions to perform various operations such as arithmetic operations, statistical calculations, sorting, filtering, solving linear equations and much more. This makes NumPy a powerful tool for scientific and engineering computing.

Advantages of using NumPy arrays over standard Python lists:

* High Performance: NumPy array operations are much faster than regular Python list operations thanks to the use of optimized C algorithms.

* Convenience and simplicity: NumPy provides a simple and convenient interface for working with arrays, which makes the code more readable and understandable.

* More Features: NumPy provides a rich selection of functions for performing array operations, making it easier to solve a wide range of scientific computing and data analysis problems.

* Integration with other libraries: NumPy integrates with other popular Python libraries such as SciPy, Matplotlib, and Pandas, making it part of an ecosystem of scientific and engineering computing tools.

## Creating NumPy Arrays

NumPy is usually imported as **"np"** for ease of use. It is common name among programmers

In [1]:
import numpy as np

In NumPy, to create one-dimensional arrays, you can use the numpy.array() function, which takes a list (or other iterable) as an argument and creates a one-dimensional array from it.

In [ ]:
# Creating a one-dimensional array from a list
arr1 = np.array([1, 2, 3, 4, 5])
print("Array arr1:", arr1)

# Creating a one-dimensional array from a tuple
arr2 = np.array((6, 7, 8, 9, 10))
print("Array arr2:", arr2)

#Creating a one-dimensional array from a range of numbers
arr3 = np.arange(1, 6)  # Creates an array with numbers from 1 to 5 (not including 6)
print("Array arr3:", arr3)


Array arr1: [1 2 3 4 5]
Array arr2: [ 6  7  8  9 10]
Array arr3: [1 2 3 4 5]


The numpy.array() function is also used to create multidimensional arrays

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Two-dimensional array arr2d:")
print(arr2d)

arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("3D array arr3d:")
print(arr3d)

random_arr = np.random.rand(2, 3)  # Creates a 2x3 array filled with random numbers from 0 to 1

print("Array random_arr (random numbers):")
print(random_arr)


Two-dimensional array arr2d:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
3D array arr3d:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Array random_arr (random numbers):
[[0.90797796 0.18797606 0.2089435 ]
 [0.53905944 0.58331531 0.82099393]]


NumPy has several built-in functions for creating arrays with specific values.

1. np.zeros(shape): Creates an array of a given shape, filled with zeros.

In [ ]:
zeros_arr = np.zeros((2, 3))
print("Array filled with zeros:")
print(zeros_arr)


Array filled with zeros:
[[0. 0. 0.]
 [0. 0. 0.]]


2. np.ones(shape): Creates an array of a given shape filled with 1.

In [ ]:
ones_arr = np.ones((3, 2))
print("An array filled with ones:")
print(ones_arr)


An array filled with ones:
[[1. 1.]
 [1. 1.]
 [1. 1.]]


3. np.empty(shape): Creates an array of the given shape, but does not initialize it with values. Instead, the array may contain arbitrary values ​​that were in the corresponding memory area before the array was created.

In [ ]:
empty_arr = np.empty((2, 2))
print("Empty array:")
print(empty_arr)


Empty array:
[[4.91475798e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]


4. np.arange(start, stop, step): Creates a one-dimensional array with values ​​from start to stop with the given step.

In [ ]:
arange_arr = np.arange(0, 10, 2)
print("Array created with arange():")
print(arange_arr)


Array created with arange():
[0 2 4 6 8]


5. np.linspace(start, stop, num): Creates a one-dimensional array with evenly distributed elements ranging from start to stop (inclusive).

In [ ]:
linspace_arr = np.linspace(0, 1, 5)
print("Array created with linspace():")
print(linspace_arr)


Array created with linspace():
[0.   0.25 0.5  0.75 1.  ]


## Basic operations with NumPy arrays

Array indexing and slicing in NumPy works similarly to lists in Python, but with additional capabilities for working with multidimensional arrays

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Referring to an array element by index
print("First element:", arr[0])

print("Last element:", arr[-1])

print("Slice from the second to the fourth element:", arr[1:4])

print("Slice with every 2 numbers", arr[::2])


First element: 1
Last element: 5
Slice from the second to the fourth element: [2 3 4]
Slice with every 2 numbers [1 3 5]


To access an element of a two-dimensional array, a array of indices is used

In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Element in second row and second column:", arr_2d[1, 1])

print("Subarray from a two-dimensional array:")
print(arr_2d[:2, 1:])


print("Slice in increments of 2 across columns:")
print(arr_2d[:, ::2])


Element in second row and second column: 5
Subarray from a two-dimensional array:
[[2 3]
 [5 6]]
Slice in increments of 2 across columns:
[[1 3]
 [4 6]
 [7 9]]


More accessing elements using index arrays:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
indices = np.array([0, 2, 4])
print(arr[indices])

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Creating an array of indexes for rows and columns
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])

#Indexing the arr_2d array using index arrays
result = arr_2d[row_indices, col_indices]

print(result)

[1 3 5]
[2 6 7]


Indexing and slicing using conditions:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[arr > 2])

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[arr_2d > 5])


[3 4 5]
[6 7 8 9]


Indexing and slicing in multidimensional arrays:

In multidimensional arrays, you can use multiple indexes or slices to access elements or subarrays. Slices in a multidimensional array are also specified using start:stop:step for each dimension, separated by commas.

In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[:2, 1:])


[[2 3]
 [5 6]]


In [ ]:
print(arr2d[:, ::2])


[[1 3]
 [4 6]
 [7 9]]


In NumPy, array arithmetic is performed element-by-element:

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 + arr2)
print(arr1 + 10)



[5 7 9]
[11 12 13]


In [ ]:
print(arr1 - arr2)
print(arr1 - 10)


[-3 -3 -3]
[-9 -8 -7]


In [ ]:
print(arr1 * arr2)
print(arr1 * 10)


[ 4 10 18]
[10 20 30]


In [ ]:
print(arr1 / arr2)
print(arr1 / 10)


[0.25 0.4  0.5 ]
[0.1 0.2 0.3]


In [ ]:
print(arr1 ** arr2)
print(arr1 ** 2)


[  1  32 729]
[1 4 9]


NumPy provides many basic mathematical functions for working with arrays of data. These functions can be applied to arrays element by element. Below are just a few examples of basic math functions in NumPy. A more detailed list of functions and additional features can be found in the official NumPy documentation.

In [ ]:
arr1 = np.array([0, np.pi/2, np.pi])
#np.sin(): Calculates the sine of an angle for each array element.
print("Sine of array elements:", np.sin(arr1))
#np.cos(): Calculates the cosine of the angle for each array element.
print("Cosine of array elements:", np.cos(arr1))
#np.tan(): Calculates the tangent of an angle for each array element.
print("Tangent of array elements:", np.tan(arr1))


Sine of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cosine of array elements: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
Tangent of array elements: [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [ ]:
arr2 = np.array([1, 2, 3])
#np.exp(): Calculates the exponent (e^x) for each array element.
print("Exponent for each array element:", np.exp(arr2))


Exponent for each array element: [ 2.71828183  7.3890561  20.08553692]


In [ ]:
arr3 = np.array([1, np.e, np.e**2])
#np.exp(): Calculates the natural logarithm for each array element.
print("Natural logarithm for each array element.", np.log(arr3))


Calculates the natural logarithm for each array element. [0. 1. 2.]


In [ ]:
arr4 = np.array([4, 9, 16])
#np.exp(): Calculates the square root of each array element.
print("Square root for each array element:", np.sqrt(arr4))


Square root for each array element: [2. 3. 4.]


If we are working with vectors, we can also calculate their dot and cross product using the np.dot() and np.cross() functions.

In [ ]:
vec1 = np.array([1, 2, 3])
vec2 = np.array([4, 5, 6])

print("Cross product of vectors vec1 and vec2: ",np.cross(vec1, vec2))
print("Dot product of vectors vec1 and vec2: ",np.dot(vec1, vec2))

Cross product of vectors vec1 and vec2:  [-3  6 -3]
Dot product of vectors vec1 and vec2:  32


Using the definition of the mixed product $(a×b)⋅c$, we can calculate it too using a combination of the np.cross() and np.dot() functions

In [ ]:
vec3 = np.array([7, 8, 9])

print("Mixed product of vectors vec1, vec2 и vec3:", np.dot(np.cross(vec1, vec2), vec3))

Mixed product of vectors vec1, vec2 и vec3: 0


##Practice

###1)
Create a 4x5 two-dimensional array filled with random numbers  ranging from 0 to 10.
Find the average of all array elements.
Create a new array in which each element of the original array is increased by the average value from the previous step and for each element find its sine, exponent, natural logarithm and square root.

###2)
Create a two-dimensional 6x6 array filled with numbers from 0 to 35.
Select and display a subarray consisting of 3 rows and 3 columns of the second quarter of the array.
Create an array from all even elements of the original array and display it on the screen.

###3)
Create two vectors vec1 and vec2 of length 3 elements. Fill them in with any integers of your choice.
Find and display scalar
and the cross product of the vectors vec1 and vec2.
Create a third vector vec3 similar way to the first two
and calculate the mixed product $(vec1 × vec2) ⋅ vec3$ and display the result.