In [ ]:
import numpy as np

In NumPy, matrices are two-dimensional arrays that have special properties and properties useful for linear algebras and matrix manipulation.

A matrix can be created by passing a list of lists (or other iterable object) to the np.array() function

In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


NumPy provides some special functions for creating certain types of matrices.
1. Matrix of zeros (np.zeros()):

A matrix of zeros consists of all elements equal to zero.

In [ ]:
# Сreating a 2x3 matrix of zeros
zeros_matrix = np.zeros((2, 3))
print(zeros_matrix)


[[0. 0. 0.]
 [0. 0. 0.]]


2. Matrix of ones (np.ones()):

A matrix of ones consists of all elements equal to one.

In [ ]:
# Сreating a 2x3 matrix of ones
ones_matrix = np.ones((3, 2))
print(ones_matrix)


[[1. 1.]
 [1. 1.]
 [1. 1.]]


3. Identity matrix (np.eye()):

The identity matrix (or identity operator) is a square matrix with all elements on the main diagonal equal to 1 and all others equal to 0.

In [ ]:
# Creating a 3x3 identity matrix
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Diagonal matrix (np.diag()):

A diagonal matrix has non-zero elements only on the main diagonal.

In [ ]:
# Creating a 3x3 diagonal matrix
diagonal_matrix = np.diag([1, 2, 3])
print(diagonal_matrix)


[[1 0 0]
 [0 2 0]
 [0 0 3]]


5. Matrix with a given value (np.full()):

A matrix with a given value contains all elements equal to a specific value

In [ ]:
# Creating a matrix with given values
constant_matrix = np.full((2, 3), 5)
print(constant_matrix)


[[5 5 5]
 [5 5 5]]


NumPy also provides methods for generating matrices with random values.

In [ ]:
random_matrix1 = np.random.rand(2, 3)
print(random_matrix1)

random_matrix2 = np.random.randint(10, size=(3, 2))
print(random_matrix2)


[[0.96724696 0.85198786 0.94743091]
 [0.71636589 0.77264582 0.34596159]]
[[2 5]
 [4 5]
 [7 1]]


These are some of the most common preset matrices in NumPy.

In NumPy, arrays, including matrices, have several basic attributes that provide information about their shape and size. Some of them:

1. shape:

The shape attribute returns a tuple representing the dimension of the array. For a matrix, this would be a tuple with two elements, where the first element represents the number of rows and the second element represents the number of columns.

2. ndim:

The ndim attribute returns the number of dimensions (axes) of the array. For a matrix it will always be 2, since a matrix is ​​a two-dimensional array.

3. size:

The size attribute returns the total number of elements in the array.

4. real и imag:

If the array contains complex numbers, the real and imag attributes represent the real and imaginary parts, respectively.

In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Matrix shape:", matrix.shape)
print("Number of dimensions (ndim) of the matrix:", matrix.ndim)
print("The total number of elements (size) of the matrix:", matrix.size)


Matrix shape: (3, 3)
Number of dimensions (ndim) of the matrix: 2
The total number of elements (size) of the matrix: 9


In [ ]:
arr_complex = np.array([[1 + 2j, 3 + 4j], [5 + 6j, 7 + 8j]])

print("Real part:", arr_complex.real)
print("Imaginary part (imag):", arr_complex.imag)


Real part: [[1. 3.]
 [5. 7.]]
Imaginary part (imag): [[2. 4.]
 [6. 8.]]


In the last lesson we looked at arithmetic operations on arrays. The same functionality is present regarding matrices.

* Addition and subtraction:

Addition and subtraction of matrices occurs element by element. The operators + and - are used for this.

In [ ]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

print(matrix1 + matrix2)


[[ 6  8]
 [10 12]]


In [ ]:
print(matrix1 - matrix2)

[[-4 -4]
 [-4 -4]]


* Multiplication:

Matrix multiplication can also be element-wise or matrix standart, depending on the use of the * operator or the np.dot() function

In [ ]:
print(matrix1 * matrix2)


[[ 5 12]
 [21 32]]


In [ ]:
print(np.dot(matrix1, matrix2))


[[19 22]
 [43 50]]


* Division:

The division of matrices also occurs element by element. The / operator is used

In [ ]:
print(matrix1 / matrix2)


[[0.2        0.33333333]
 [0.42857143 0.5       ]]


Also, NumPy methods provide the ability to transpose a matrix, find the determinant, rank, trace, inverse matrix, and more.

Matrix transposition can be done using the .T method or the np.transpose() function

In [ ]:
print (matrix1.T)


[[1 3]
 [2 4]]


In [ ]:
print (np.transpose(matrix1))


[[1 3]
 [2 4]]


The trace can be found using np.trace().

In [ ]:
print(np.trace(matrix1))


5


The determinant, inverse matrix and rank can be found using the np.linalg.det() and np.linalg.inv() functions; we’ll look at them and the np.linalg submodule a little later

##Practice

###1)
Create 2 3 by 3 matrices with random natural numbers. Perform element-by-element addition and subtraction, multiplication and division of these matrices and display the results on the screen.
Perform matrix multiplication on matrix1 and matrix2 and display the result.

###2)
Create a 4x4 square matrix containing values ​​from 0 to 15.
Find and display this matrix's trace, determinant and rank
If the determinant of a matrix is ​​not zero, find and display the inverse of the matrix.

###3)
Create a 5x4 matrix with numbers from 0 to 100 evenly distributed.
Transpose the matrix.
Compare the dimensions of the original and transposed matrices.