Don't forget to import NumPy!

In [ ]:
import numpy as np

This time we'll take a closer look at np.linalg and working with some linear algebra problems.

np.linalg is a module of the NumPy library that provides functions for working with linear algebra. This module contains many functions that allow you to perform various operations and calculations related to linear algebra, such as calculating the determinant, inverse matrix, eigenvalues ​​and vectors, singular value decomposition, solving systems of linear equations, and much more.


Solving systems of linear equations is finding the values ​​of the variables that satisfy all the equations in the system. NumPy uses the np.linalg.solve() function to solve such systems.

A system of linear equations is usually written in matrix form Ax = b, where A is a matrix of coefficients, x is a vector of variables, b is a vector of the right side of the equations.

For example, the solution for the following system of equations:
\begin{cases}
   2x + 3y = 5,
   \\
   4x - y = -2
 \end{cases}



In [ ]:
# Coefficient matrix
A = np.array([[2, 3], [4, -1]])

# Vector of the right side of the equations
b = np.array([5, -2])

# Solving a system of linear equations
solution = np.linalg.solve(A, b)

print("Solution of the system:")
print("x =", solution[0])
print("y =", solution[1])

Solution of the system:
x = -0.07142857142857145
y = 1.7142857142857142


## Determinant, inverse matrix and rank.

With np.linalg we can finally calculate the determinant, inverse of the matrix, and rank of the matrix.



In [ ]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 10]])

# Calculation of the determinant of a matrix
determinant = np.linalg.det(matrix)

# Calculating the inverse matrix
inverse_matrix = np.linalg.inv(matrix)

# Calculating Matrix Rank
rank = np.linalg.matrix_rank(matrix)

print("Matrix determinant:", determinant)
print("Inverse matrix:")
print(inverse_matrix)
print("Matrix rank:", rank)

Matrix determinant: -2.9999999999999996
Inverse matrix:
[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]
Matrix rank: 3


## Matrix decompositions

np.linalg provides functions for some matrix decompositions, for example:


1. Singular decomposition ($SVD$)

$SVD$ is a method of decomposing a matrix into the product of three simpler matrices:
$A=U⋅Σ⋅V^T$, where
A - original matrix,
U и V - orthogonal matrices (matrices satisfying the condition
$U ^T⋅U=I$ и $V^T⋅V=I$, where
$I$ - identity matrix), а
$Σ$ - a diagonal matrix containing the singular values ​​of the original matrix.

$SVD$ Widely used in data analysis, image compression, recommender systems and other fields.

In [ ]:
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

# Calculation of singular decomposition
U, Sigma, Vt = np.linalg.svd(A)

print("U:")
print(U)
print("Sigma:")
print(Sigma)
print("Vt:")
print(Vt)


U:
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Sigma:
[9.52551809 0.51430058]
Vt:
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


2. Cholesky decomposition:

The Cholesky decomposition applies to symmetric and positive definite matrices. It represents the matrix
$A$ as a product
$A=L⋅L^T$, where
$L$ is a lower triangular matrix.

This decomposition is used in solving systems of linear equations, simulating random processes, filtering signals, and other applications.

In [ ]:
B = np.array([[4, 12, -16],
              [12, 37, -43],
              [-16, -43, 98]])

# Calculating the Cholesky decomposition
L = np.linalg.cholesky(B)

print("Lower triangular matrix L:")
print(L)

#Let's check if its correct
reconstructed_B = np.dot(L, L.T)

print("\nOriginal matrix B:")
print(B)
print("\nRecovered matrix B from the Cholesky decomposition:")
print(reconstructed_B)
print("Are B and reconstructed_B equal?", np.allclose(B, reconstructed_B))

Lower triangular matrix L:
[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]

Original matrix B:
[[  4  12 -16]
 [ 12  37 -43]
 [-16 -43  98]]

Recovered matrix B from the Cholesky decomposition:
[[  4.  12. -16.]
 [ 12.  37. -43.]
 [-16. -43.  98.]]
Are B and reconstructed_B equal? True



The np.allclose() function checks whether the corresponding elements of two arrays are equal within some margin of error.

3. QR decomposition:

QR decomposition represents the matrix
$A$ as a product
$A=QR$, where
$Q$ is an orthogonal matrix, and
$R$ is an upper triangular matrix.

QR decomposition is used in linear regression problems, calculating matrix eigenvalues, basis orthogonalization and other problems.

In [ ]:
С = np.array([[1, -1, 2],
              [1, 1, 0],
              [1, -1, 2]])

# Calculation of QR decomposition
Q, R = np.linalg.qr(С)

print("Q (orthogonal matrix):")
print(Q)
print("R (upper triangular matrix):")
print(R)


reconstructed_C = np.dot(Q, R)

print("\n Original matrix C:")
print(C)
print("\nRecovered matrix B from QR decomposition:")
print(reconstructed_C)
print("Are C и reconstructed_C equal?", np.allclose(C, reconstructed_C))

Q (orthogonal matrix):
[[-0.57735027  0.40824829 -0.70710678]
 [-0.57735027 -0.81649658  0.        ]
 [-0.57735027  0.40824829  0.70710678]]
R (upper triangular matrix):
[[-1.73205081e+00  5.77350269e-01 -2.30940108e+00]
 [ 0.00000000e+00 -1.63299316e+00  1.63299316e+00]
 [ 0.00000000e+00  0.00000000e+00 -5.55111512e-17]]

 Original matrix C:
[[ 1 -1  2]
 [ 1  1  0]
 [ 1 -1  2]]

Recovered matrix B from QR decomposition:
[[ 1.00000000e+00 -1.00000000e+00  2.00000000e+00]
 [ 1.00000000e+00  1.00000000e+00 -6.23553335e-16]
 [ 1.00000000e+00 -1.00000000e+00  2.00000000e+00]]
Are C и reconstructed_C equal? True


## Vector and matrix norm:

In NumPy, you can use the numpy.linalg.norm() function to calculate the norm of a vector (vector length). This function takes a vector and an optional parameter ord, which specifies the order of the norm. The default order (if not specified) is 2, which corresponds to the Euclidean norm.

In [ ]:
vector = np.array([3, 4])
print(np.linalg.norm(vector))


5.0


You can also calculate the norm of a matrix using the numpy.linalg.norm() function in NumPy

In [ ]:
matrix = np.array([[1, 2], [3, 4]])
print(np.linalg.norm(matrix))


5.477225575051661


## Eigenvalues ​​and eigenvectors



Eigenvalues ​​and eigenvectors are important linear algebra concepts that are widely used in various fields, including machine learning, physics, engineering, and others. In NumPy, the numpy.linalg.eig() function is used to calculate the eigenvalues ​​and eigenvectors of a matrix.

Eigenvalues ​​and eigenvectors:
Eigenvalues ​​and eigenvectors of a matrix
$A$ are defined in such a way that:
For a square matrix
$A$ and scalar
$λ$ there is a nonzero vector
$v$, such that
$Av=λv$. Here
$v$ is called an eigenvector, and
$λ$ - eigenvalue.



In [ ]:
matrix = np.array([[1, 2], [2, 1]])

# Calculation of eigenvalues ​​and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:")
for i in range(len(eigenvalues)):
    print("Eigenvalue:", eigenvalues[i])
    print("The corresponding eigenvector is:", eigenvectors[:,i])


Eigenvalues: [ 3. -1.]
Eigenvectors:
Eigenvalue: 3.0000000000000004
The corresponding eigenvector is: [0.70710678 0.70710678]
Eigenvalue: -0.9999999999999996
The corresponding eigenvector is: [-0.70710678  0.70710678]


##Practice

###1)
Solve this system of equations:
\begin{cases}
   3x_1 + 8x_2 + 5x_3 - 8x_4 = -44,
   \\
   10x_1 + 6x_2 + -x_3 + 5x_4 = -45,
   \\
   4x_1 + 4x_2 + 5x_3 - 8x_4 = -45,
   \\
   -24x_1 - 20x_2 + 9x_3 - 28x_4 = 75,
   \\
 \end{cases}

###2)
Find SVD and LU decomposition for matrix
\begin{pmatrix}
  2& -1& 0 \\
  -1& 1& 1 \\
  0& 1& 2 \\
\end{pmatrix}

###3)
Create a 4x4 matrix using random integers ranging from 1 to 10.
Find the determinant of the matrix.
If the determinant is not zero, find the inverse of the matrix.
Find the rank.

### 4)
Matrix A is equal to
\begin{pmatrix}
  1& 1& 1& 0\\
  1& 1& 0& 1\\
  1& 0& 1& 1\\
  0& 1& 1& 1\\
\end{pmatrix}
Find eigenvalues ​​and eigenvectors of a matrix
Check if for each eigenvalue and corresponding eigenvector
$A⋅v=λ⋅v$